Shinorama
KikeDeAlba/sell-point-uas-project pull request #4
Opened 2024-04-27 22:35 UTC by Shinogm

2024-04-27 22:39 UTC, KikeDeAlba commented
Remueve lo de si no tienes cuenta, en este proyecto, no puedes crearte una cuenta, el administrador debe creartela, asi que eso esta mal

src/components/login-form.astro
![image](https://github.com/KikeDeAlba/sell-point-uas-project/assets/78590985/19c07096-875b-42de-b9e4-25b9aa83c8d6)

2024-04-27 22:56 UTC, KikeDeAlba requested changes
Resuelve los conflictos comentados en los archivos

2024-04-27 22:56 UTC, KikeDeAlba commented on src/components/login-form.astro
Remueve este codigo
![image](https://github.com/KikeDeAlba/sell-point-uas-project/assets/78590985/5f3e7a0e-6a90-4881-91f6-222c4ca6b9da)

2024-04-27 22:56 UTC, KikeDeAlba commented on src/pages/dashboard.astro
# Tus consultas no son async / await y eso hace que estes complicando el codigo y que puedas tener errores
haz que tus consultas utilicen async / await
![image](https://github.com/KikeDeAlba/sell-point-uas-project/assets/78590985/773f2d0f-c835-4123-b44c-a18022e54d71)

2024-04-27 22:56 UTC, KikeDeAlba commented on src/pages/dashboard.astro
Cambia esto para que no haga un map a atravez de una promesa

![image](https://github.com/KikeDeAlba/sell-point-uas-project/assets/78590985/fd031613-e99a-4e09-95c9-d793b1c4d9e8)

2024-04-27 23:29 UTC, Shinogm commented on src/pages/dashboard.astro
![image](https://github.com/KikeDeAlba/sell-point-uas-project/assets/138961421/64a07ebe-82d6-4012-95ec-d6c23324cbec)

2024-04-27 23:30 UTC, Shinogm commented on src/pages/dashboard.astro
nomas esa no jala atirros (volteado)

2024-04-27 23:35 UTC, KikeDeAlba requested changes
completa el where de manera correcta usando la funcion eq

2024-04-27 23:35 UTC, KikeDeAlba commented on src/pages/dashboard.astro
En la que no te jalo tienes mal el where, recuerda que para comparar dos valores tienes que usar eq

2024-04-28 00:21 UTC, merged

2024-04-28 00:31 UTC, Shinogm commented
![image](https://github.com/KikeDeAlba/sell-point-uas-project/assets/138961421/6748d1ee-6dae-446a-9021-9001edf50d7e)